# Generated by Django 3.2.6 on 2021-08-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='basket_subjects',
        ),
        migrations.AddField(
            model_name='user',
            name='basket_subjects',
            field=models.ManyToManyField(to='classs.Class', verbose_name='장바구니 과목들'),
        ),
    ]
