# Generated by Django 3.2.6 on 2021-08-11 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='basket_subjects',
            field=models.TextField(blank=True, null=True, verbose_name='장바구니 과목들'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, null=True, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(max_length=15, null=True, verbose_name='전공'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.PositiveIntegerField(default=20140000, validators=[django.core.validators.MinValueValidator(20140000), django.core.validators.MaxValueValidator(99999999)], verbose_name='학번'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registed_subjects',
            field=models.TextField(blank=True, null=True, verbose_name='수강신청 과목들'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_table',
            field=models.TextField(blank=True, null=True, verbose_name='시간표'),
        ),
    ]
