# Generated by Django 3.2.6 on 2021-08-12 01:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210812_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registed_subjects',
        ),
        migrations.AddField(
            model_name='user',
            name='registed_subjects',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='수강신청 과목들'),
        ),
    ]
