# Generated by Django 3.2.6 on 2021-08-10 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basket_subjects',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registed_subjects',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='time_table',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
