# Generated by Django 3.2.6 on 2021-08-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210810_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
