# Generated by Django 3.2.6 on 2021-09-28 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='basket_subjects',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registed_subjects',
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='학번'),
        ),
    ]
