# Generated by Django 3.2.7 on 2021-09-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='basket_subjects',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registed_subjects',
        ),
    ]
