# Generated by Django 3.2.6 on 2021-10-10 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basketLists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='time_table',
            field=models.JSONField(blank=True, null=True, verbose_name='시간표'),
        ),
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
