# Generated by Django 3.2.7 on 2021-10-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketLists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='time_table',
            field=models.JSONField(default={}, verbose_name='시간표'),
        ),
    ]
