# Generated by Django 3.2.6 on 2021-10-23 12:33

import basketLists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketLists', '0002_auto_20211010_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time_table',
            field=models.JSONField(default=basketLists.models.default_time_table_dict, null=True, verbose_name='시간표'),
        ),
    ]
