# Generated by Django 3.2.7 on 2021-10-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketLists', '0003_alter_list_time_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time_table',
            field=models.JSONField(default=dict, verbose_name='시간표'),
        ),
    ]
