# Generated by Django 3.2.6 on 2021-10-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_registration_credits'),
        ('basketLists', '0003_alter_list_time_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
        migrations.CreateModel(
            name='List',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('registrations.registration',),
        ),
    ]
