# Generated by Django 3.2.6 on 2021-10-24 03:21

import basketLists.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0005_class_people'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basketLists', '0004_auto_20211023_2154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_table', models.JSONField(default=basketLists.models.default_time_table_dict, null=True, verbose_name='시간표')),
                ('credits', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='신청학점')),
                ('subjects', models.ManyToManyField(blank=True, to='classs.Class')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
