# Generated by Django 3.2.7 on 2021-10-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketLists', '0008_alter_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time_table',
            field=models.JSONField(blank=True, null=True, verbose_name='시간표'),
        ),
    ]
