# Generated by Django 3.2.7 on 2021-10-16 15:07

import basketLists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketLists', '0011_alter_list_time_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time_table',
            field=models.JSONField(default=basketLists.models.default_time_table_dict, null=True, verbose_name='시간표'),
        ),
    ]
