# Generated by Django 3.2.7 on 2021-10-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_alter_registration_credits'),
        ('basketLists', '0012_alter_list_time_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
        migrations.CreateModel(
            name='List',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('registrations.registration',),
        ),
    ]
