# Generated by Django 3.2.6 on 2021-08-11 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='baskets',
            fields=[
                ('class_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classs.class')),
                ('available', models.PositiveIntegerField(default=0)),
                ('left', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('classs.class',),
        ),
    ]
