# Generated by Django 3.2.6 on 2021-08-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0002_alter_class_check_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('공통', '공통')], default='--선택--', max_length=2, verbose_name='학년'),
        ),
    ]
