# Generated by Django 3.2.6 on 2021-08-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0003_rename_baskets_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('class_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classs.class')),
                ('regi_list', models.TextField(verbose_name='수강신청 과목 리스트')),
            ],
            options={
                'abstract': False,
            },
            bases=('classs.class',),
        ),
    ]
