# Generated by Django 3.2.6 on 2021-09-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0004_auto_20210831_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='people',
            field=models.PositiveIntegerField(default=0, verbose_name='수강 가능인원'),
        ),
    ]
