# Generated by Django 3.2.6 on 2021-08-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0004_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='department',
            new_name='개설학과',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='subject_name',
            new_name='과목명',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='subject_number',
            new_name='과목번호',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='professor',
            new_name='담당교수',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='check_major',
            new_name='이수구분',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='is_closed',
            new_name='폐강여부',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='grade',
            new_name='학년',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='credit',
            new_name='학점',
        ),
    ]
