# Generated by Django 3.2.6 on 2021-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0005_auto_20210811_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='개설학과',
        ),
        migrations.RemoveField(
            model_name='class',
            name='과목명',
        ),
        migrations.RemoveField(
            model_name='class',
            name='과목번호',
        ),
        migrations.RemoveField(
            model_name='class',
            name='담당교수',
        ),
        migrations.RemoveField(
            model_name='class',
            name='이수구분',
        ),
        migrations.RemoveField(
            model_name='class',
            name='폐강여부',
        ),
        migrations.RemoveField(
            model_name='class',
            name='학년',
        ),
        migrations.RemoveField(
            model_name='class',
            name='학점',
        ),
        migrations.AddField(
            model_name='class',
            name='check_major',
            field=models.CharField(choices=[('majaor', '전공'), ('electives', '교양')], default='--선택--', max_length=10, verbose_name='이수구분'),
        ),
        migrations.AddField(
            model_name='class',
            name='credit',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, verbose_name='학점'),
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.CharField(blank=True, max_length=20, verbose_name='개설학과'),
        ),
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='--선택--', max_length=2, verbose_name='학년'),
        ),
        migrations.AddField(
            model_name='class',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='폐강'),
        ),
        migrations.AddField(
            model_name='class',
            name='professor',
            field=models.CharField(blank=True, max_length=5, verbose_name='담당교수'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='과목명'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='과목번호'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='available',
            field=models.PositiveIntegerField(default=0, verbose_name='수강 가능 인원수'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='left',
            field=models.PositiveIntegerField(default=0, verbose_name='여석'),
        ),
    ]
