# Generated by Django 3.2.6 on 2021-08-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0006_auto_20210811_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='class_ptr',
        ),
        migrations.DeleteModel(
            name='basket',
        ),
        migrations.DeleteModel(
            name='registration',
        ),
    ]
