# Generated by Django 3.2.6 on 2021-08-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0006_alter_class_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.CharField(blank=True, choices=[('경제학과', '경제학과'), ('전자공학과', '전자공학과'), ('소프트웨어학과', '소프트웨어학과')], default='--선택--', max_length=20, verbose_name='개설학과'),
        ),
    ]
