# Generated by Django 3.2.6 on 2021-08-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0007_alter_class_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='credit',
            field=models.CharField(blank=True, max_length=2, verbose_name='학점'),
        ),
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.CharField(blank=True, default='--선택--', max_length=20, verbose_name='개설학과'),
        ),
    ]
