# Generated by Django 3.2.7 on 2021-09-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0008_auto_20210831_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='people',
            field=models.PositiveIntegerField(default=0, verbose_name='수강인원'),
        ),
    ]
