# Generated by Django 3.2.7 on 2021-09-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0009_class_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='people',
            field=models.PositiveIntegerField(default=0, verbose_name='수강 가능인원'),
        ),
    ]
