# Generated by Django 3.2.6 on 2021-08-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='--선택--', max_length=2, verbose_name='학년')),
                ('check_major', models.CharField(choices=[('majaor', '전공'), ('electives', '교양')], default='--선택--', max_length=10, verbose_name='이수구분')),
                ('subject_number', models.CharField(blank=True, max_length=20, verbose_name='과목번호')),
                ('subject_name', models.CharField(blank=True, max_length=30, verbose_name='과목명')),
                ('credit', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, verbose_name='학점')),
                ('professor', models.CharField(blank=True, max_length=5, verbose_name='담당교수')),
                ('is_closed', models.BooleanField(default=False, verbose_name='폐강')),
                ('available', models.PositiveIntegerField(default=0, verbose_name='수강 가능 인원수')),
                ('left', models.PositiveIntegerField(default=0, verbose_name='여석')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
