# Generated by Django 3.2.6 on 2021-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2)),
                ('check_major', models.CharField(choices=[('majaor', '전공'), ('electives', '교양')], default='--선택--', max_length=10)),
                ('subject_number', models.CharField(blank=True, max_length=20)),
                ('subject_name', models.CharField(blank=True, max_length=30)),
                ('credit', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2)),
                ('professor', models.CharField(blank=True, max_length=5)),
                ('is_closed', models.BooleanField(default=False)),
                ('class_list', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
