# Generated by Django 3.2.6 on 2021-09-28 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0005_class_people'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0004_auto_20210831_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='check_major',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='regi_list',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='subject_number',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='time',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='universe',
        ),
        migrations.AddField(
            model_name='registration',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='classs.Class'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resgistration', to=settings.AUTH_USER_MODEL),
        ),
    ]
