# Generated by Django 3.2.6 on 2021-10-23 12:33

from django.db import migrations, models
import registrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20210928_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='time_table',
            field=models.JSONField(default=registrations.models.default_time_table_dict, null=True, verbose_name='시간표'),
        ),
    ]
