# Generated by Django 3.2.7 on 2021-10-16 15:25

from django.db import migrations, models
import registrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_auto_20210928_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='time_table',
            field=models.JSONField(default=registrations.models.default_time_table_dict, null=True, verbose_name='시간표'),
        ),
    ]
