<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-08-11 11:28
=======
# Generated by Django 3.2.6 on 2021-08-10 11:53
>>>>>>> d1d70430256434a060ae14edf690af07eed49e46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
<<<<<<< HEAD
                ('title', models.CharField(max_length=50)),
=======
                ('title', models.CharField(default='제목을 입력하세요', max_length=50)),
>>>>>>> d1d70430256434a060ae14edf690af07eed49e46
                ('content', models.TextField(verbose_name='내용을 입력하세요')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
