# Generated by Django 3.2.6 on 2021-08-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(verbose_name='내용을 입력하세요')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
