# Generated by Django 3.2.6 on 2021-08-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeBoards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='number',
        ),
        migrations.AddField(
            model_name='notice',
            name='department',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000014CC66F6CD0>', max_length=10, verbose_name='소속'),
        ),
        migrations.AddField(
            model_name='notice',
            name='post_hit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notice',
            name='type',
            field=models.CharField(choices=[('notation', '공지'), ('question', '문의')], default='--선택--', max_length=10, verbose_name='종류'),
        ),
        migrations.AddField(
            model_name='notice',
            name='writer',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000014CC66E2670><django.db.models.query_utils.DeferredAttribute object at 0x0000014CC66E2610>', max_length=20, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(default='내용을 입력하세요', verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
    ]
