# Generated by Django 3.2.6 on 2021-08-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeBoards', '0002_auto_20210824_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.CharField(default='', max_length=10, verbose_name='소속'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='writer',
            field=models.CharField(default='', max_length=20, verbose_name='작성자'),
        ),
    ]
