# Generated by Django 3.2.6 on 2021-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeBoards', '0003_auto_20210824_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(default='', verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='post_hit',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
