# Generated by Django 3.2.6 on 2021-08-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeBoards', '0004_auto_20210824_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='type',
            field=models.CharField(choices=[('공지', '공지'), ('문의', '문의')], default='--선택--', max_length=10, verbose_name='종류'),
        ),
    ]
