# Generated by Django 3.2.7 on 2021-09-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeBoards', '0005_alter_notice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='post_hit',
        ),
    ]
