# Generated by Django 3.2.7 on 2021-09-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeBoards', '0006_remove_notice_post_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='post_hit',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
